environment: dev

deployment:
  image:  
    tag: 0
  replicas: 1
  env:
    redis_host: master.crud-dev-elascache-rep-group.tkllca.use1.cache.amazonaws.com

secret:
  redis_pass: automate-all-the-things-dev
