environment: stage

deployment:
  image:
    tag: 1
  replicas: 1
  env:
    redis_host: master.crud-stage-elascache-rep-group.tkllca.use1.cache.amazonaws.com

secret:
  redis_pass: automate-all-the-things-stage
